<template>
  <div class="app">
    <div v-if="store.$state.isAuthorized" @click="clearStore" class="logout-btn">
      Выйти
    </div>
    <div class="loading" v-if="store.isLoading">
      <div class="loading__inner">
        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" width="200" height="200" style="shape-rendering: auto; display: block; background: rgba(255,255,255,0);" xmlns:xlink="http://www.w3.org/1999/xlink"><g><circle r="20" fill="#e90c59" cy="50" cx="30">
          <animate begin="-0.5s" values="30;70;30" keyTimes="0;0.5;1" dur="1s" repeatCount="indefinite" attributeName="cx"></animate>
        </circle>
          <circle r="20" fill="#46dff0" cy="50" cx="70">
            <animate begin="0s" values="30;70;30" keyTimes="0;0.5;1" dur="1s" repeatCount="indefinite" attributeName="cx"></animate>
          </circle>
          <circle r="20" fill="#e90c59" cy="50" cx="30">
            <animate begin="-0.5s" values="30;70;30" keyTimes="0;0.5;1" dur="1s" repeatCount="indefinite" attributeName="cx"></animate>
            <animate repeatCount="indefinite" dur="1s" keyTimes="0;0.499;0.5;1" calcMode="discrete" values="0;0;1;1" attributeName="fill-opacity"></animate>
          </circle><g></g></g><!-- [ldio] generated by https://loading.io --></svg>
      </div>
    </div>
    <component :is="currentComponent" />
  </div>
</template>

<script lang="ts" setup>
import {computed, onMounted, watch} from 'vue'
import { useUserStore } from './stores/user'
import AuthView from './views/AuthView.vue'
import EnterNameView from './views/EnterNameView.vue'
import SelectTableView from './views/SelectTableView.vue'
import QueueView from './views/QueueView.vue'
import ReceivedView from './views/ReceivedView.vue'
import {storeToRefs} from "pinia";

const store = useUserStore()

const { isAuthorized, user, inQueue } = storeToRefs(useUserStore())

onMounted(() => {
  store.checkAuth()
})

const currentComponent = computed(() => {
  if (!isAuthorized.value) return AuthView
  if (!user.value?.name) return EnterNameView
  if (!user.value?.table) return SelectTableView
  return inQueue.value ? ReceivedView : QueueView
})

const clearStore = () => {
  localStorage.removeItem('user')
  localStorage.removeItem('badge')
  window.location.reload()
}
</script>

<style scoped>
.app {
  font-size: 1.5rem;
  padding: 2rem;
  font-family: sans-serif;
}
.logout-btn {
  position: absolute;
  right: 30px;
  top: 2.5rem;
  cursor: pointer;
}

.loading{
  position: absolute;
  width: 100%;
  height: 100%;
  left: 0;
  top:0;
  background-color: rgba(0,0,0,.3);
}
.loading__inner{
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
}
</style>

<style>
h2{
  padding-right: 80px;
}
</style>